# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4230fa5498c792c1d299850560ffa9f1a7b990194a596ad418505c2e5fcebe03087035afdc041f553ae893514139ce0bc8f3a46f0f2be9e6c7dd5d66c92011ca

test:
  secret_key_base: 080178b8a2a9d5dd600a05d11335800ce709f82959adb8b9096f78c7d0d3ca961bc0cc4f5d6b7759e7403521e85023625f0459d21896c10e11d63b0f7cec3646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
